### ISSUE TITLE
Erreur 500 à l'enregistrement sur le site de demo

### ISSUE THREAD

**Issue by thierrymarianne** [Sharepear/Sharepear#6]
Une idée de ce dont il pourrait s'agir ? L'erreur n'est pas reproductible après installation locale.

**Comment by kosssi** [comment]
Hiiii, merci je viens de regarder les logs : 
 Duplicate entry 'gordon freeman' for key 'UNIQ_957A647992FC23A8'

**Comment by thierrymarianne** [comment]
Merci ! Il ne faut donc pas tenter de s'inscrire avec un nom déjà existant :)

**Comment by kosssi** [comment]
Ou il faudrait ajouter un message pour dire que l'username est déjà existant ;)

**Comment by kosssi** [comment]
J'ai ajouter l'issue #10
