### ISSUE TITLE
PHP exif extension required

### ISSUE THREAD

**Issue by thierrymarianne** [Sharepear/Sharepear#7]
```
Attempted to call function "exif_read_data" from namespace "kosssi\MyAlbumsBundle\Helper" in /Users/labodev/repositories/sharepear/src/kosssi/MyAlbumsBundle/Helper/ImageExifHelper.php line 21
```

Souhaiterais-tu rendre l'usage (après installation) de l'extension exif obligatoire ? 
Je ne suis pas certain qu'elle soit comprise dans les installations par défaut de php sur les distributions usuels.

On peut 
 * ajouter une mention à propos de ce pré-requis dans la documentation ou dans le fichier de description interprété par `composer`.
 * rendre obligatoire [l'installation de l'extension](http://php.net/manual/en/book.exif.php) voir PR https://github.com/Sharepear/Sharepear/pull/8

**Comment by kosssi** [comment]
Merci pour la PR
